# Generated by Django 4.1.7 on 2023-05-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_alter_room_name_meassage_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='meassage',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
    ]
